spring:
  application:
    name: eureka server
  security:
    basic:
      enable: true
    user:
      name: ciphercard-eureka-user
      password: aerdkcucrp-rhsae-eeriu

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false